# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortener
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway Configuration (Runs your V1 script automatically)
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# Hibernate / JPA settings
# Set to 'validate' so Hibernate checks your entities against Flyway's tables
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true